### ISSUE TITLE
team in multiple teams?

### ISSUE THREAD

**Issue by hopewise** [mpociot/teamwork#23]
Is there a possibility to assign a user to multiple teams? as you have used team_user table? is this supported with your package apis?

**Comment by mpociot** [comment]
Sure, since the user to teams relation is a `hasMany` relation, a user can join multiple teams.

Just call `$user->attachTeam($team);` multiple times.

To list all teams that the user has joined, you can access the relation through: `$user->teams`.

Also take a look at the documentation covering the topic of switching the current active team: https://github.com/mpociot/teamwork#switching-the-current-team

**Comment by hopewise** [comment]
Thank you!
