### ISSUE TITLE
UUID Suport

### ISSUE THREAD

**Issue by ahpetrot** [mpociot/teamwork#43]
Support for UUID?

**Comment by mpociot** [comment]
Wow...could you please spend 5 more minutes to write a github issue that is actually useful?

**Comment by ahpetrot** [comment]
My bad !! I got sucked into a few different tasks all at once and didn't provide a full feature description.  That wasn't my original intent and I am sorry.

UUID support would be pretty awesome sauce from several different prospectives.  I think the portability of the team/user from one app to another ( think poor man's replication ) would be useful.   Perhaps a quick cli or api for export/import would be useful as well. 

Thanks !

**Comment by lukasoppermann** [comment]
Hey, I would appreciate this as well. I am not sure if there is a way to check the type of `key` used in the `User` model, before creating the migration? Otherwise an explanation in the Readme would be nice, like: "Just change the team_id and user_id, here, here and here to a Varchar xyz". 

But would this actually work? If I had used a varchar on the user model and also changed the migrations, would this break the package?

**Comment by mpociot** [comment]
I haven't tried it myself, but if you just change the migration file to have a varchar instead of an unsigned integer should be enough.

Would be cool if one of you could test this. I'll add a note on the README in that case.

**Comment by lukasoppermann** [comment]
I will try to test it today.

**Comment by mpociot** [comment]
Thank you :)

**Comment by lukasoppermann** [comment]
I only tried using a uuid for the user model. However by updating the migrations creating a team with a user (with uuid) as well as assigning a team to a user (with auto-current-team) worked fine.

I have not time testing the team uuid, it probably works as well. 😄 

Anyway a readme update would be very nice! 👍

**Comment by mpociot** [comment]
Thanks for testing the UUID feature.
It would've surprised me if there were issues regarding that.

I'll make some changes to the README / documentation.
