### ISSUE TITLE
Non-team member can invite members to team

### ISSUE THREAD

**Issue by vmitchell85** [mpociot/teamwork#53]
If I create a account and go to the team URL (`/teams/members/1`) I can invite people to that team even if I'm not a member myself. So, in effect I could join myself to any team.

I did notice #50 where it was sugessted that certain restrictions be put in place for inviting, but I thought that this just seems inaccurate for the default.

**Comment by mikemclin** [comment]
I think you should not view it as the "default" but rather completely unopinionated (it does nothing).  The package doesn't touch ACL's at all, which I think is a good thing.  If you're using this package, then I would assume you already have some sort of ACL layer in place, be it Laravel Gates, Policies or whatever.

Who can invite users?  The team owner?  A member?  A moderator?  Someone who has been a member for over 30 days?  You can see how baking something seemingly harmless like this into the library becomes a slippery slope.  Here is a simple example how you'd use Laravel Gates to limit invites to only the team owner.

## Example using Laravel Gates

```php
// Wherever you place your Gates
Gate::define('invite-user', function ($user, $team) {
    return $user->isOwnerOfTeam($team);
});

// Inside the controller/service that invites users
if (Gate::allows('invite-user', $team)) {
    Teamwork::inviteToTeam( $email, $team, function( $invite )
    {
        // Send email to user / let them know that they got invited
    });
}
```

**Comment by vmitchell85** [comment]
@mikemclin I understand what you mean but I find it odd that you can invite someone to a team that you **aren't** even a member of. The other scenarios you mention make sense but I feel like if I'm not a member of a certain team I shouldn't be able to invite people to it.

**Comment by mikemclin** [comment]
Any nominations-based team would be a good example of a team that I am not a part of, but would like to add someone else to.

Also, maybe nobody sends the invite.  Maybe the website (a system user?) itself sends out the invite because some sort of criteria was met (you got 50 likes, you are now invited to the "Elite Authors" team).  Who knows.

However, I do think that demonstrating Laravel Gates or Policies in the documentation would be helpful for users.  If you think about it, it is sort of refreshing that there are no permissions associated with the library.  You make it do whatever you want, however you want, instead of having to learn about which permissions the lib has implemented, and what the methods are for overriding those permissions so you can make it work how you want.

**Comment by jlndk** [comment]
A solution that could work for everybody would be a small entry in the config file that enables the protection.
Example:
```php
<?php
// /config/teamwork.php
return [
    //...
   `validateOnlyMemberCanInvite` => false
];
?>
```

We could set it to default true, which would give better security out of the box, but a veeery smal learning curve for those who want to disable it. We could also set it to default false, which would provide that unopinionanted "blank slate" while still shipping protection with the package. However people would actually need to enable it to get the protection

**Comment by vmitchell85** [comment]
I think a config would be a great option. I do feel like most use cases would be to not allow non-members to invite people so I'd be in favor of defaulting to true.

Maybe I'll work on a PR to add this...

**Comment by mpociot** [comment]
I will work on a PR to add this 👍
